# Generated by Django 3.2.5 on 2021-07-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='is_successful',
            field=models.BooleanField(default=True),
        ),
    ]
